apiVersion: v1
kind: Config
clusters:
- name: nombre-del-cluster
  cluster:
    certificate-authority-data: CERTIFICATE_AUTHORITY_BASE64
    server: https://dirección-del-cluster
contexts:
- name: nombre-del-contexto
  context:
    cluster: nombre-del-cluster
    user: nombre-del-usuario
current-context: nombre-del-contexto
users:
- name: nombre-del-usuario
  user:
    client-certificate-data: CLIENT_CERTIFICATE_BASE64
    client-key-data: CLIENT_KEY_BASE64